[package]
name = "quadgraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.glfw]
version = "0.51.0"
default-features = false
